name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo badblocks nbd-client
          version: 1.0

      - name: Load nbd module
        run: sudo modprobe nbd

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ramdisk
        run: |
          sudo cargo run -p nbd-ramdisk --release &
          sleep 5
      
      - name: Make a NBD device
        run: sudo nbd-client localhost 10809 /dev/nbd0